export const INITIATE_PAYMENT_REQUEST = "INITIATE_PAYMENT_REQUEST";
export const INITIATE_PAYMENT_SUCCESS = "INITIATE_PAYMENT_SUCCESS";
export const INITIATE_PAYMENT_FAILURE = "INITIATE_PAYMENT_FAILURE";

export const PAYMENT_CALLBACK_REQUEST = "PAYMENT_CALLBACK_REQUEST";
export const PAYMENT_CALLBACK_SUCCESS = "PAYMENT_CALLBACK_SUCCESS";
export const PAYMENT_CALLBACK_FAILURE = "PAYMENT_CALLBACK_FAILURE";

export const GET_PAYMENT_STATUS_REQUEST = "GET_PAYMENT_STATUS_REQUEST";
export const GET_PAYMENT_STATUS_SUCCESS = "GET_PAYMENT_STATUS_SUCCESS";
export const GET_PAYMENT_STATUS_FAILURE = "GET_PAYMENT_STATUS_FAILURE";
